version: "3"
services:
  nginx:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80" # 宿主机端口:容器端口
    restart: always
    container_name: hcxw_nginx

  authserver:
    build:
      context: ./authserver
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # 宿主机端口:容器端口
    restart: always
    volumes:
      - "./authserver_web:/home/authserver/web" # 容器目录挂载到宿主机目录
    container_name: hcxw_authserver

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "3100:3100" # 宿主机端口:容器端口
    restart: always
    volumes:
      - "./webserver_web:/home/webserver/web" # 容器目录挂载到宿主机目录
    container_name: hcxw_webserver
    # networks: 
    #   - mynet

  mysql:
    image: mysql:5.7
    restart: always
    container_name: hcxw_mysql
    ports:
      - "3306:3306" # 宿主机端口:容器端口
    environment:
      - "TZ=Asia/Shanghai" # 设置容器时区与宿主机保持一致
      - "MYSQL_ROOT_PASSWORD=123456" # 设置root密码
      - "MYSQL_DATABASE=ocrnationalserviceplatform" # 创建数据库ocrnationalserviceplatform，初始化会在此数据库中执行
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # 设置容器时区与宿主机保持一致
      - "./mysql/db:/var/lib/mysql" # 映射数据库保存目录到宿主机，防止数据丢失
      - "./mysql/conf/my.cnf:/etc/my.cnf"
      # 如果宿主机mysql/db目录不为空，则不会执行数据库初始化
      - "./mysql/init:/docker-entrypoint-initdb.d/"   # 数据库初始化
    # networks: 
    #   - mynet
    
# networks:
#   mynet:
#     external: true
